### ISSUE TITLE
Couldn't bridge to Goerli from Near

### ISSUE THREAD

**Issue by SagorSakib7** [Electron-Labs/testnet2.0-issues#16]
The bridge takes awfully long time and it's still pending , it has been 12 hours or so since i initiated the bridge still it didn't gone through . I also initiated a couple of transaction but the result is the same. Please fix that . If this isn't solved today  ,how come we'll get NFT from Galxe? Please keep this in mind. Thank you

**Comment by smol-ninja** [comment]
relayed issue.
