### ISSUE TITLE
Error while approving

### ISSUE THREAD

**Issue by Mamay84** [Electron-Labs/testnet2.0-issues#2]
![11](https://user-images.githubusercontent.com/96120707/235921636-07f927ca-3e4a-4818-9b5c-83f117bf1bdc.jpg)
![22](https://user-images.githubusercontent.com/96120707/235921647-83ab0976-9667-4708-bfc1-ec726c0ad924.jpg)
![33](https://user-images.githubusercontent.com/96120707/235921658-541ba017-e7d9-4074-947b-d1aed7e00e40.jpg)

**Comment by dpathania95** [comment]
@Mamay84 we have resolved the issue at our end
