### ISSUE TITLE
No POP UP or any notification for the transaction, whether it is succeeded or not  

### ISSUE THREAD

**Issue by Jadviq** [Electron-Labs/testnet2.0-issues#21]
No POP UP or any notification for the transaction, whether it is succeeded or not. It shows only as SIGNING in the wallet, nothing else. . No transaction history to track your transaction.
![image](https://github.com/Electron-Labs/testnet2.0-issues/assets/128990768/8366e379-fe60-477d-a1f3-d6a98f4170e8)
![image](https://github.com/Electron-Labs/testnet2.0-issues/assets/128990768/f2483b57-de01-4b59-84b2-ba957dc2e79e)
My Near Wallet - 5d955961543fc58d21c2edadf01dfa5e347b7ed69ce02610a2a2241503ae3c8d

**Comment by dpathania95** [comment]
@Jadviq We have resolved the issue
