### ISSUE TITLE
cannot verify tweet links in order to use faucets

### ISSUE THREAD

**Issue by ChrisDDobry** [Electron-Labs/testnet2.0-issues#25]
the issue works the same for every token present in faucets

**Comment by ChrisDDobry** [comment]
issue is still present, I'm unable to use faucets as they won't verify my tweets > i'm unable to finish the testnet
Can i get any answer before closing the ticket?

**Comment by smol-ninja** [comment]
Please share your tweet link.

**Comment by ChrisDDobry** [comment]
https://twitter.com/ChrisDDobry/status/1678433013191901185?s=20

**Comment by smol-ninja** [comment]
fixed this issue.
