### ISSUE TITLE
Failure to swap

### ISSUE THREAD

**Issue by taku0x** [Electron-Labs/testnet2.0-issues#27]
the zkbridge returns to the default zkUSDC on the swap tab making it impossible to swap USDC as shown below
![electron](https://github.com/Electron-Labs/testnet2.0-issues/assets/132532124/fdbb9acd-fb0c-4247-9e94-40ae71fd4226)
however the pool section can see the amount of USDC I have
![electron2](https://github.com/Electron-Labs/testnet2.0-issues/assets/132532124/77085512-8333-4b9f-9e3a-ebb2b563d5e0)

**Comment by smol-ninja** [comment]
Hello @taku0x, while I am not able to clearly understand the issue, you can swap between zkUSDC.e and USDC.e on https://mainnet.electronlabs.org/liquidity-pool/usdc?pool-type=swap if thats what you need.

And for this, can you provide steps to reproduce the issue?

**Comment by taku0x** [comment]
I understand what you have said and I've noticed it was a problem with my meteor wallet pop up

**Comment by smol-ninja** [comment]
Happy to know that it worked.
