### ISSUE TITLE
can't faucet usdc 

### ISSUE THREAD

**Issue by Kantez** [Electron-Labs/testnet2.0-issues#5]
click on transfer but nothing happened

**Comment by yokoyolk** [comment]
me too , i confirm transaction in metamask success but system show unable to transfer token .

**Comment by dpathania95** [comment]
@Kantez @yokoyolk Can you please share some details about the steps?

**Comment by yokoyolk** [comment]
I can request now.

ในวันที่ จ. 15 พ.ค. 2023 เวลา 17:02 Divyanshu Pathania <
***@***.***> เขียนว่า:

**Comment by smol-ninja** [comment]
Issue resolved by user.
