### ISSUE TITLE
failure of transfer eUSDC from Goerli to Near

### ISSUE THREAD

**Issue by kirakira-max** [Electron-Labs/testnet2.0-issues#6]
When trying to bridge eUSDC, I see this error message "execution reverted: ERC20: insufficient allowance".

**Comment by thesatyajat** [comment]
it requires recipient address but i am giving the address it do not allow me to paste or type here any address

**Comment by dpathania95** [comment]
@thesatyajat there is an option to enter the address manually. Please click on Enter Manually button to enter the address

**Comment by dpathania95** [comment]
@kirakira-max Are you still facing the issue?
