### ISSUE TITLE
Completed bridges display bug

### ISSUE THREAD

**Issue by LoDeFi3192** [Electron-Labs/testnet2.0-issues#8]
![Capture d'écran 2023-05-09 205412](https://github.com/Electron-Labs/testnet2.0-issues/assets/119480912/a0b3a1d4-4eac-4a6b-8da0-2aa9f3a3606c)

**Comment by Suthipong1988** [comment]
![elec](https://github.com/Electron-Labs/testnet2.0-issues/assets/101257176/0309b4d1-5873-4410-87e8-1df7a547b58e)

**Comment by dpathania95** [comment]
@Suthipong1988 Is the issue resolved for you, otherwise can you please share the browser details

**Comment by LoDeFi3192** [comment]
yeah, everything looks good now, thanks

**Comment by dpathania95** [comment]
Closing the issue since it got resolved
